name = "cloudflare-chat-app"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "chat-db"
database_id = "ac4b55a6-25ad-4931-9021-2f73c098fa83"

[[kv_namespaces]]
binding = "CHAT_KV"
id = "945ff7625f9c458697b0429bc4ac7ce0"

[[durable_objects.bindings]]
name = "CHAT_ROOM"
class_name = "ChatRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatRoom"]
